// Code generated by "stringer -type=acc"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[read-1]
	_ = x[write-2]
	_ = x[readWrite-3]
	_ = x[subscribe-4]
}

const _acc_name = "readwritereadWritesubscribe"

var _acc_index = [...]uint8{0, 4, 9, 18, 27}

func (i acc) String() string {
	i -= 1
	if i >= acc(len(_acc_index)-1) {
		return "acc(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _acc_name[_acc_index[i]:_acc_index[i+1]]
}
